language: ruby
rvm:
- 2.3.0
before_script:
- psql -c 'create database deploy_spork_test;' -U postgres
script: bundle exec rspec spec
bundler_args: --without development
addons:
  postgresql: 9.3
sudo: false
